### ISSUE TITLE
instance Show for Smiles

### ISSUE THREAD

**Issue by artemkondyukov** [klangner/radium#6]
It would be useful for getting the clue about internal representation of molecule.

**Comment by klangner** [comment]
Good idea. I will add it

**Comment by klangner** [comment]
Done. Do you need new version on https://hackage.haskell.org/?

**Comment by artemkondyukov** [comment]
Thank you!

By now I’ve done it and use forked version for further figuring out how to deal with it.

**Comment by klangner** [comment]
Sure. That would be great :-)

**Comment by klangner** [comment]
This is already done.
